# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_cul_mat_fun2 <- function(mat_input, core_num) {
    .Call(`_EMMMLE_log_cul_mat_fun2`, mat_input, core_num)
}

likelihood_weight <- function(data_use, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num) {
    .Call(`_EMMMLE_likelihood_weight`, data_use, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num)
}

log_likelihood_fun <- function(data_input, mu_mat, sigma_list, pi_vec, S_depth, t_root_vec, omega_root_vec) {
    .Call(`_EMMMLE_log_likelihood_fun`, data_input, mu_mat, sigma_list, pi_vec, S_depth, t_root_vec, omega_root_vec)
}

compute_weight_Z <- function(data_input, weight_init, mlemu_init, mlesigmahat_init, S_depth, t_root_vec, omega_root_vec) {
    .Call(`_EMMMLE_compute_weight_Z`, data_input, weight_init, mlemu_init, mlesigmahat_init, S_depth, t_root_vec, omega_root_vec)
}

EMMMLE_weighted_step1 <- function(data_use, cond_Z_input, S_depth, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num) {
    .Call(`_EMMMLE_EMMMLE_weighted_step1`, data_use, cond_Z_input, S_depth, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num)
}

EMMMLE_weighted_step2 <- function(data_use, cond_Z_input, S_depth, res_mmle1, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num) {
    .Call(`_EMMMLE_EMMMLE_weighted_step2`, data_use, cond_Z_input, S_depth, res_mmle1, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num)
}

EMMMLE_sigma12_fun <- function(data_use, cond_Z_input, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num) {
    .Call(`_EMMMLE_EMMMLE_sigma12_fun`, data_use, cond_Z_input, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num)
}

EMMMLE_newton_fun <- function(data_use_arma, cond_Z_input_arma, S_depth_arma, res_init_mu_arma, res_init_sigma_arma, t_root_vec_arma, omega_root_vec_arma, k_max, core_num, cut_num) {
    .Call(`_EMMMLE_EMMMLE_newton_fun`, data_use_arma, cond_Z_input_arma, S_depth_arma, res_init_mu_arma, res_init_sigma_arma, t_root_vec_arma, omega_root_vec_arma, k_max, core_num, cut_num)
}

EMMMLE_main <- function(data_input, pi_init, mlemu_init, mlesigmahat_init, S_depth, t_root_vec, omega_root_vec, iter_max, omega, p_p_post_dist_Z, k_max, cut_num) {
    .Call(`_EMMMLE_EMMMLE_main`, data_input, pi_init, mlemu_init, mlesigmahat_init, S_depth, t_root_vec, omega_root_vec, iter_max, omega, p_p_post_dist_Z, k_max, cut_num)
}

EMMMLE <- function(data_obs, pi_init, mu_initial_all, sigma_inital_all, S_depth, t_root_vec, omega_root_vec, p_p_post_dist_Z, k_max, position_input, core_num, omega, iter_max, cut_num) {
    .Call(`_EMMMLE_EMMMLE`, data_obs, pi_init, mu_initial_all, sigma_inital_all, S_depth, t_root_vec, omega_root_vec, p_p_post_dist_Z, k_max, position_input, core_num, omega, iter_max, cut_num)
}

Update_log_cond_prob_X <- function(mu, precision_mat, Xdata, scale, eps = 1e-6, max_iter = 100L, core_num = 1L) {
    .Call(`_EMMMLE_Update_log_cond_prob_X`, mu, precision_mat, Xdata, scale, eps, max_iter, core_num)
}

soft <- function(A, a_mat, diag = 0L) {
    .Call(`_EMMMLE_soft`, A, a_mat, diag)
}

equal1 <- function(X, lambda, weight_mat, zero_mat, err = 10^(-5), maxIter = 10^3L, rho = 1, diag = 0L, core_num = 1L) {
    .Call(`_EMMMLE_equal1`, X, lambda, weight_mat, zero_mat, err, maxIter, rho, diag, core_num)
}

equal2 <- function(X, lambda, weight_mat, zero_mat, err = 10^(-5), maxIter = 10^3L, rho = 1, diag = 0L, core_num = 1L) {
    .Call(`_EMMMLE_equal2`, X, lambda, weight_mat, zero_mat, err, maxIter, rho, diag, core_num)
}

log_cul_mat_fun1 <- function(mat) {
    .Call(`_EMMMLE_log_cul_mat_fun1`, mat)
}

mmle_weighted_step1 <- function(data_use, cond_Z_input, S_depth, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num) {
    .Call(`_EMMMLE_mmle_weighted_step1`, data_use, cond_Z_input, S_depth, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num)
}

mmle_weighted_step2 <- function(data_use, cond_Z_input, S_depth, convergence_vec, update_mat, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num) {
    .Call(`_EMMMLE_mmle_weighted_step2`, data_use, cond_Z_input, S_depth, convergence_vec, update_mat, mu_init, sigma_init, t_root_vec, omega_root_vec, k_max, core_num, cut_num)
}

Update_sigma12_fun <- function(data_use, cond_Z_input, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num, position_input) {
    .Call(`_EMMMLE_Update_sigma12_fun`, data_use, cond_Z_input, S_depth, mlemu1, mlesigmahat1, t_root_vec, omega_root_vec, core_num, position_input)
}

basic_mmle <- function(data_use, S_depth, mlemu1, mlesigmahat1, gradiant_int, Hessian_int, core_num) {
    .Call(`_EMMMLE_basic_mmle`, data_use, S_depth, mlemu1, mlesigmahat1, gradiant_int, Hessian_int, core_num)
}

mmle_newton_fun <- function(data_use, cond_Z_input, S_depth, res_init_mu, res_init_sigma, t_root_vec, omega_root_vec, k_max, core_num, position_input, cut_num) {
    .Call(`_EMMMLE_mmle_newton_fun`, data_use, cond_Z_input, S_depth, res_init_mu, res_init_sigma, t_root_vec, omega_root_vec, k_max, core_num, position_input, cut_num)
}

